#!/usr/bin/env ruby

require "lgit"

if ARGV.size.zero?
  puts 'Specify command'
  exit 1
end

git = Lgit::Git.new

case ARGV[0]
when 'branch'
  git.create_branch ARGV[1]
when 'rebase'
  if git.get_branch == 'master'
    puts "Error: Cannot rebase master!"
    exit 2
  end
  git.rebase
when 'delete-branches'
  git.delete_branches
else
  puts 'Invalid command'
  exit 3
end

