#!/usr/bin/env ruby
# frozen_string_literal: true

require 'lgit'

if ARGV.size.zero?
  puts 'Specify command'
  exit 1
end

git = Lgit::Git.new

case ARGV[0]
when 'branch'
  git.create_branch(ARGV[1], ARGV[2])
when 'rebase'
  if git.get_branch == 'master'
    puts 'Error: Cannot rebase master!'
    exit 2
  end
  git.rebase ARGV[1]
when 'delete-branches'
  git.delete_branches
else
  puts 'Invalid command'
  exit 3
end

